-- sql/005_hu11_gestion_admision.sql
-- ============================================================
-- HU-11 / RF11: Gestion de admision
-- Registra el ingreso del paciente, verifica datos y motivo de
-- consulta, y asigna medico o sala sin duplicar el trabajo previo.
-- ============================================================

-- ============================================================
-- ENUMS
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_admision_enum') THEN
    CREATE TYPE tipo_admision_enum AS ENUM (
      'consulta_externa',
      'emergencia',
      'hospitalizacion'
    );
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_admision_enum') THEN
    CREATE TYPE estado_admision_enum AS ENUM (
      'registrada',
      'en_triage',
      'asignada',
      'atendida',
      'cancelada'
    );
  END IF;
END;
$$;

-- ============================================================
-- TABLA ADMISION
-- ============================================================

CREATE TABLE IF NOT EXISTS admision
(
  id_admision INTEGER GENERATED BY DEFAULT AS IDENTITY,

  id_paciente INTEGER NOT NULL,

  id_enfermero INTEGER NOT NULL,

  id_cita INTEGER,

  id_consulta INTEGER,

  id_medico INTEGER,

  tipo_admision tipo_admision_enum
    NOT NULL
    DEFAULT 'consulta_externa',

  fecha_admision TIMESTAMP
    NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  motivo_consulta TEXT
    NOT NULL,

  sala_asignada VARCHAR(50),

  datos_verificados BOOLEAN
    NOT NULL
    DEFAULT FALSE,

  estado estado_admision_enum
    NOT NULL
    DEFAULT 'registrada',

  observaciones TEXT,

  CONSTRAINT pk_admision
    PRIMARY KEY(id_admision),

  CONSTRAINT fk_admision_paciente
    FOREIGN KEY(id_paciente)
    REFERENCES paciente(id_paciente)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_admision_enfermero
    FOREIGN KEY(id_enfermero)
    REFERENCES enfermero(id_enfermero)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_admision_cita
    FOREIGN KEY(id_cita)
    REFERENCES cita(id_cita)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT fk_admision_consulta
    FOREIGN KEY(id_consulta)
    REFERENCES consulta(id_consulta)
    ON UPDATE CASCADE
    ON DELETE SET NULL,

  CONSTRAINT fk_admision_medico
    FOREIGN KEY(id_medico)
    REFERENCES medico(id_medico)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_admision_motivo
    CHECK (length(trim(motivo_consulta)) > 0),

  CONSTRAINT chk_admision_asignacion
    CHECK (id_medico IS NOT NULL OR sala_asignada IS NOT NULL),

  CONSTRAINT chk_admision_verificada
    CHECK (
      estado IN ('registrada', 'cancelada')
      OR datos_verificados = TRUE
    )
);

-- Evita dos admisiones para la misma cita/consulta.
CREATE UNIQUE INDEX IF NOT EXISTS uq_admision_cita
ON admision(id_cita)
WHERE id_cita IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_admision_consulta
ON admision(id_consulta)
WHERE id_consulta IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_admision_paciente
ON admision(id_paciente);

CREATE INDEX IF NOT EXISTS idx_admision_enfermero
ON admision(id_enfermero);

CREATE INDEX IF NOT EXISTS idx_admision_medico
ON admision(id_medico);

CREATE INDEX IF NOT EXISTS idx_admision_fecha
ON admision(fecha_admision);

CREATE INDEX IF NOT EXISTS idx_admision_estado
ON admision(estado);

-- ============================================================
-- FUNCION: VALIDAR ADMISION
-- ============================================================

CREATE OR REPLACE FUNCTION fn_validar_admision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
DECLARE
  v_id_paciente INTEGER;
  v_id_medico INTEGER;
  v_estado_cita TEXT;
BEGIN
  NEW.motivo_consulta := trim(NEW.motivo_consulta);

  IF NEW.id_cita IS NOT NULL THEN
    SELECT c.id_paciente, c.id_medico, c.estado::TEXT
    INTO v_id_paciente, v_id_medico, v_estado_cita
    FROM cita c
    WHERE c.id_cita = NEW.id_cita;

    IF v_id_paciente IS NULL THEN
      RAISE EXCEPTION 'La cita % no existe.', NEW.id_cita;
    END IF;

    IF v_id_paciente <> NEW.id_paciente THEN
      RAISE EXCEPTION 'La cita % no pertenece al paciente %.', NEW.id_cita, NEW.id_paciente;
    END IF;

    IF v_estado_cita = 'cancelada' THEN
      RAISE EXCEPTION 'No se puede admitir una cita cancelada.';
    END IF;

    IF NEW.id_medico IS NULL THEN
      NEW.id_medico := v_id_medico;
    ELSIF NEW.id_medico <> v_id_medico THEN
      RAISE EXCEPTION 'El medico de admision no coincide con el medico de la consulta %.', NEW.id_consulta;
    END IF;
  END IF;

  IF NEW.id_consulta IS NOT NULL THEN
    SELECT c.id_paciente, c.id_medico
    INTO v_id_paciente, v_id_medico
    FROM consulta c
    WHERE c.id_consulta = NEW.id_consulta;

    IF v_id_paciente IS NULL THEN
      RAISE EXCEPTION 'La consulta % no existe.', NEW.id_consulta;
    END IF;

    IF v_id_paciente <> NEW.id_paciente THEN
      RAISE EXCEPTION 'La consulta % no pertenece al paciente %.', NEW.id_consulta, NEW.id_paciente;
    END IF;

    IF NEW.id_medico IS NULL THEN
      NEW.id_medico := v_id_medico;
    ELSIF NEW.id_medico <> v_id_medico THEN
      RAISE EXCEPTION 'El medico de admision no coincide con el medico de la cita %.', NEW.id_cita;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_admision ON admision;

CREATE TRIGGER trg_validar_admision
BEFORE INSERT OR UPDATE
ON admision
FOR EACH ROW
EXECUTE FUNCTION fn_validar_admision();

-- ============================================================
-- FUNCION: REGISTRAR ADMISION
-- ============================================================

DROP FUNCTION IF EXISTS fn_registrar_admision(
  INTEGER,
  INTEGER,
  TEXT,
  tipo_admision_enum,
  INTEGER,
  INTEGER,
  VARCHAR,
  BOOLEAN,
  TEXT
);

CREATE OR REPLACE FUNCTION fn_registrar_admision(
  p_id_paciente INTEGER,
  p_id_enfermero INTEGER,
  p_motivo_consulta TEXT,
  p_tipo_admision VARCHAR DEFAULT 'consulta_externa',
  p_id_cita INTEGER DEFAULT NULL,
  p_id_medico INTEGER DEFAULT NULL,
  p_sala_asignada VARCHAR DEFAULT NULL,
  p_datos_verificados BOOLEAN DEFAULT TRUE,
  p_observaciones TEXT DEFAULT NULL
)
RETURNS TABLE(
  id_admision INTEGER,
  id_consulta INTEGER,
  estado_admision estado_admision_enum,
  mensaje TEXT
)
LANGUAGE plpgsql
AS
$$
DECLARE
  v_id_medico INTEGER;
  v_id_consulta INTEGER;
  v_id_admision INTEGER;
BEGIN
  IF p_id_paciente IS NULL THEN
    RAISE EXCEPTION 'Debe indicar el paciente.';
  END IF;

  IF p_id_enfermero IS NULL THEN
    RAISE EXCEPTION 'Debe indicar el enfermero responsable de admision.';
  END IF;

  IF p_motivo_consulta IS NULL OR length(trim(p_motivo_consulta)) = 0 THEN
    RAISE EXCEPTION 'Debe registrar el motivo de consulta.';
  END IF;

  IF p_id_cita IS NOT NULL THEN
    SELECT c.id_medico
    INTO v_id_medico
    FROM cita c
    WHERE c.id_cita = p_id_cita
      AND c.id_paciente = p_id_paciente
      AND c.estado <> 'cancelada';

    IF v_id_medico IS NULL THEN
      RAISE EXCEPTION 'La cita indicada no existe, no pertenece al paciente o esta cancelada.';
    END IF;
  ELSE
    v_id_medico := p_id_medico;
  END IF;

  IF p_id_medico IS NOT NULL THEN
    v_id_medico := p_id_medico;
  END IF;

  IF v_id_medico IS NULL AND p_sala_asignada IS NULL THEN
    RAISE EXCEPTION 'Debe asignar un medico o una sala.';
  END IF;

  IF v_id_medico IS NOT NULL THEN
    IF p_id_cita IS NOT NULL THEN
      SELECT c.id_consulta
      INTO v_id_consulta
      FROM consulta c
      WHERE c.id_cita = p_id_cita;
    END IF;

    IF v_id_consulta IS NULL THEN
      INSERT INTO consulta
      (
        id_cita,
        id_paciente,
        id_medico,
        motivo_consulta,
        observaciones
      )
      VALUES
      (
        p_id_cita,
        p_id_paciente,
        v_id_medico,
        trim(p_motivo_consulta),
        p_observaciones
      )
      RETURNING consulta.id_consulta INTO v_id_consulta;
    END IF;
  END IF;

  INSERT INTO admision
  (
    id_paciente,
    id_enfermero,
    id_cita,
    id_consulta,
    id_medico,
    tipo_admision,
    motivo_consulta,
    sala_asignada,
    datos_verificados,
    estado,
    observaciones
  )
  VALUES
  (
    p_id_paciente,
    p_id_enfermero,
    p_id_cita,
    v_id_consulta,
    v_id_medico,
    p_tipo_admision::tipo_admision_enum,
    trim(p_motivo_consulta),
    p_sala_asignada,
    COALESCE(p_datos_verificados, FALSE),
    CASE
      WHEN COALESCE(p_datos_verificados, FALSE) = TRUE THEN 'asignada'::estado_admision_enum
      ELSE 'registrada'::estado_admision_enum
    END,
    p_observaciones
  )
  RETURNING admision.id_admision, admision.estado
  INTO v_id_admision, estado_admision;

  id_admision := v_id_admision;
  id_consulta := v_id_consulta;
  mensaje := 'Admision registrada correctamente.';

  RETURN NEXT;
END;
$$;

-- ============================================================
-- TRIGGER: SINCRONIZAR CITA AL ADMITIR
-- ============================================================

CREATE OR REPLACE FUNCTION fn_sincronizar_cita_admision()
RETURNS TRIGGER
LANGUAGE plpgsql
AS
$$
BEGIN
  IF NEW.id_cita IS NOT NULL AND NEW.estado <> 'cancelada' THEN
    UPDATE cita
    SET estado = 'confirmada'
    WHERE id_cita = NEW.id_cita
      AND estado = 'pendiente';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sincronizar_cita_admision ON admision;

CREATE TRIGGER trg_sincronizar_cita_admision
AFTER INSERT
ON admision
FOR EACH ROW
EXECUTE FUNCTION fn_sincronizar_cita_admision();

-- ============================================================
-- VISTA: ADMISIONES
-- ============================================================

CREATE OR REPLACE VIEW vw_admisiones AS
SELECT
  a.id_admision,
  a.fecha_admision,
  a.tipo_admision,
  a.estado,
  a.datos_verificados,
  a.motivo_consulta,
  a.sala_asignada,
  a.observaciones,
  p.id_paciente,
  per_p.nombre AS paciente_nombre,
  per_p.apellido AS paciente_apellido,
  a.id_cita,
  ci.fecha_hora AS fecha_cita,
  a.id_consulta,
  a.id_enfermero,
  per_e.nombre AS enfermero_nombre,
  per_e.apellido AS enfermero_apellido,
  a.id_medico,
  per_m.nombre AS medico_nombre,
  per_m.apellido AS medico_apellido
FROM admision a
INNER JOIN paciente p
  ON p.id_paciente = a.id_paciente
INNER JOIN persona per_p
  ON per_p.persona_id = p.persona_id
INNER JOIN enfermero e
  ON e.id_enfermero = a.id_enfermero
INNER JOIN persona per_e
  ON per_e.persona_id = e.persona_id
LEFT JOIN medico m
  ON m.id_medico = a.id_medico
LEFT JOIN persona per_m
  ON per_m.persona_id = m.persona_id
LEFT JOIN cita ci
  ON ci.id_cita = a.id_cita;

COMMENT ON TABLE admision IS
'Registro de admision del paciente realizado por enfermeria antes de la atencion medica.';

-- ============================================================
-- PRUEBA MANUAL
-- Cambia los IDs por registros existentes antes de ejecutar.
-- ============================================================
--
-- SELECT *
-- FROM fn_registrar_admision(
--   p_id_paciente := 1,
--   p_id_enfermero := 1,
--   p_motivo_consulta := 'Dolor abdominal',
--   p_tipo_admision := 'consulta_externa',
--   p_id_cita := 1,
--   p_datos_verificados := TRUE
-- );
--
-- SELECT *
-- FROM vw_admisiones;
